//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlService.LoadServiceReferenceCon {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoadServiceReferenceCon.ILoad")]
    public interface ILoad {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoad/LoadFeed", ReplyAction="http://tempuri.org/ILoad/LoadFeedResponse")]
        CommonLibrary.SynItems LoadFeed(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoad/LoadFeed", ReplyAction="http://tempuri.org/ILoad/LoadFeedResponse")]
        System.Threading.Tasks.Task<CommonLibrary.SynItems> LoadFeedAsync(string url);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoadChannel : ControlService.LoadServiceReferenceCon.ILoad, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoadClient : System.ServiceModel.ClientBase<ControlService.LoadServiceReferenceCon.ILoad>, ControlService.LoadServiceReferenceCon.ILoad {
        
        public LoadClient() {
        }
        
        public LoadClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoadClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoadClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoadClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CommonLibrary.SynItems LoadFeed(string url) {
            return base.Channel.LoadFeed(url);
        }
        
        public System.Threading.Tasks.Task<CommonLibrary.SynItems> LoadFeedAsync(string url) {
            return base.Channel.LoadFeedAsync(url);
        }
    }
}
