//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlService.MailServiceReferenceCon {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MailServiceReferenceCon.IMail")]
    public interface IMail {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMail/SendMail", ReplyAction="http://tempuri.org/IMail/SendMailResponse")]
        void SendMail(CommonLibrary.SynItems items, string[] recipients);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMail/SendMail", ReplyAction="http://tempuri.org/IMail/SendMailResponse")]
        System.Threading.Tasks.Task SendMailAsync(CommonLibrary.SynItems items, string[] recipients);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMailChannel : ControlService.MailServiceReferenceCon.IMail, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MailClient : System.ServiceModel.ClientBase<ControlService.MailServiceReferenceCon.IMail>, ControlService.MailServiceReferenceCon.IMail {
        
        public MailClient() {
        }
        
        public MailClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MailClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SendMail(CommonLibrary.SynItems items, string[] recipients) {
            base.Channel.SendMail(items, recipients);
        }
        
        public System.Threading.Tasks.Task SendMailAsync(CommonLibrary.SynItems items, string[] recipients) {
            return base.Channel.SendMailAsync(items, recipients);
        }
    }
}
